FROM tomcat:8.5-jre8

MAINTAINER Sébastien Vanvelthem

ENV JVM_OPTS="-Xmx4g -Xms4g -XX:MaxPermSize=1024m"

RUN apt-get update &&\
    apt-get -y install php-cgi

# Set tomcat config
#ADD tomcat/catalina.policy /usr/local/tomcat/conf/catalina.policy

# Add webapps
ADD webapps/jasper-bridge.war /usr/local/tomcat/webapps/jasper-bridge.war

CMD ["catalina.sh", "run"]

EXPOSE 8080 9267